version: '3'
services:
  mariadb:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - mariadb-volume:/etc/mysql
  php:
    build: ./php
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
      - ./data:/var/data
      - apache-volume:/etc/apache2
    depends_on:
      - mariadb
volumes:
  mariadb-volume:
  apache-volume:
